name: Run GUI checks and tests

on:
  pull_request:
  push:
    branches: 'master'

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 26
          cache: pnpm
          cache-dependency-path: 'web/pnpm-lock.yaml'

      - name: Install Project Dependencies
        run: pnpm install

      # This is needed for `pnpm check` to find the WASM code's type definitions
      - name: HACK — Build Once
        run: pnpm build

      - name: Run Svelte Check
        run: pnpm check

      - name: Run Prettier & ESLint
        run: pnpm lint
